Store configs for each release
alacritty/website pull request #34
Opened 2024-10-08 16:31 UTC by kchibisov

By clicking on a `Configuration` the user will see a list of releases where they could pick a configuration for their release.

--

It seems to work, though, not sure how great it's. Could also store `.yml` files for previous releases.

2024-10-08 16:49 UTC, chrisduerr commented
I don't think this is the best solution. I think having a dropdown on the individual configuration sites is superior and it's not that hard to implement either.

2024-10-08 16:50 UTC, chrisduerr requested changes
See my comment.

2024-10-09 00:41 UTC, chrisduerr commented
Pushed my suggestions as a change. Let me know what you think.

2024-10-09 00:53 UTC, kchibisov commented on update_config.sh
> +sed -i "s/const versions = \[/\0\n  '$version',/" ./static/select_release.js
At this point can sed urls along the way.

2024-10-09 01:14 UTC, chrisduerr commented on update_config.sh
> +sed -i "s/const versions = \[/\0\n  '$version',/" ./static/select_release.js
You mean the URLs in the changelog etc? I'm a bit conflicted on that because we aren't actually adding changelogs with this script. So we'd be replacing stuff that isn't actually created by this script.

2024-10-09 01:19 UTC, kchibisov commented on update_config.sh
> +sed -i "s/const versions = \[/\0\n  '$version',/" ./static/select_release.js
yeah, but I don't care that much. sed is fine.

2024-10-09 01:20 UTC, chrisduerr approved these changes
Let's see what breaks.

2024-10-22 23:52 UTC, merged